name: paired_name_app
description: "A paired-name generator app."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  wave_divider: ^0.0.3
  dotted_decoration: ^2.0.0
  rive: ^0.13.13
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  package_rename: ^1.7.1
  icons_launcher: ^2.1.7
  flutter_native_splash: ^2.4.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
  assets:
    - assets/images/icon.png
    - assets/rive-animations/sparkle-now.riv
