name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Extract current version from pubspec.yaml
        id: extract_version
        run: |
          current_version=$(grep '^version: ' pubspec.yaml | awk '{print $2}' | sed 's/+.*//')
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Get latest release version from GitHub
        id: get_latest_release
        run: |
          latest_version=$(gh release view --json tagName -q .tagName | sed 's/^v//')
          echo "latest_version=$latest_version" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check version difference
        if: env.current_version == env.latest_version
        run: |
          echo "No version change detected. Exiting."
          exit 0

      - name: Draft Release with Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ env.current_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog Content
        id: generate_changelog
        run: |
          changelog=$(gh release view --json body -q .body || echo "No release notes available." | tr -d '\r')
          echo "changelog=$changelog" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update CHANGELOG.md
        id: update_changelog
        run: |
          # Check if CHANGELOG.md exists; create it if not
          if [ ! -f CHANGELOG.md ]; then
            echo "CHANGELOG.md does not exist. Creating..."
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
          fi

          # Add new version entry to CHANGELOG.md only if it doesn't already exist
          if ! grep -q "## \[v${{ env.current_version }}\]" CHANGELOG.md; then
            echo "## [v${{ env.current_version }}] - $(date +'%Y-%m-%d')" >> CHANGELOG.md
            echo "$changelog" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "changes_exist=true" >> $GITHUB_ENV
          else
            echo "Version entry already exists in CHANGELOG.md. Skipping..."
            echo "changes_exist=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changelog
        if: env.changes_exist == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull origin main --rebase
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for version v${{ env.current_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
